[package]
name = "best-doggo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
tokio = { version = "1.37.0", features = ["full"] }
rand = "0.8"
serde = { version = "1", features = ["derive"] }
askama = { version = "0.12.1", features = ["with-axum", "serde", "markdown"] }
askama_axum = "0.4.0"

