services:
  todo-app-3:
    image: 'ghcr.io/parkerbedlan/best-doggo:0.0.17'
    volumes:
      - '/root/best-doggo-db:/db'
    networks:
      k0gggkw: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.306
      - coolify.serviceId=1
      - coolify.type=service
      - coolify.name=todo-app-3-k0gggkw
      - coolify.pullRequestId=0
      - coolify.service.subId=1
      - coolify.service.subType=application
      - traefik.enable=true
      - traefik.http.routers.todo-app-3.rule=Host(`todo3.parkerbedlan.com`)
      - traefik.http.routers.todo-app-3.entrypoints=https
      - traefik.http.routers.todo-app-3.tls=true
      - traefik.http.routers.todo-app-3.tls.certresolver=letsencrypt
      - traefik.http.services.todo-app-3.loadbalancer.server.port=3000
    restart: unless-stopped
    container_name: todo-app-3-k0gggkw
    environment:
      COOLIFY_CONTAINER_NAME: todo-app-3-k0gggkw
volumes: {  }
networks:
  k0gggkw:
    name: k0gggkw
    external: true
