services:
  todo-app-2:
    image: 'ghcr.io/parkerbedlan/best-doggo:0.0.16'
    volumes:
      - '/root/todo-app-db:/db'
    networks:
      b8400w0: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.306
      - coolify.serviceId=1
      - coolify.type=service
      - coolify.name=todo-app-2-b8400w0
      - coolify.pullRequestId=0
      - coolify.service.subId=1
      - coolify.service.subType=application
      - traefik.enable=true
      - traefik.http.routers.todo-app-2.rule=Host(`todo2.parkerbedlan.com`)
      - traefik.http.routers.todo-app-2.entrypoints=https
      - traefik.http.routers.todo-app-2.tls=true
      - traefik.http.routers.todo-app-2.tls.certresolver=letsencrypt
      - traefik.http.services.todo-app-2.loadbalancer.server.port=3000
    restart: unless-stopped
    container_name: todo-app-2-b8400w0
    environment:
      COOLIFY_CONTAINER_NAME: todo-app-2-b8400w0
volumes: {  }
networks:
  b8400w0:
    name: b8400w0
    external: true
